/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_school_smartcalc_model_ModelCalculator */

#ifndef _Included_edu_school_smartcalc_model_ModelCalculator
#define _Included_edu_school_smartcalc_model_ModelCalculator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_school_smartcalc_model_ModelCalculator
 * Method:    validator
 * Signature: (Ljava/lang/String;D)I
 */
JNIEXPORT jint JNICALL Java_edu_school_smartcalc_model_ModelCalculator_validator
  (JNIEnv *, jobject, jstring, jdouble);

/*
 * Class:     edu_school_smartcalc_model_ModelCalculator
 * Method:    calcExpr
 * Signature: (Ljava/lang/String;D)D
 */
JNIEXPORT jdouble JNICALL Java_edu_school_smartcalc_model_ModelCalculator_calcExpr
  (JNIEnv *, jobject, jstring, jdouble);

#ifdef __cplusplus
}
#endif
#endif
